# Utilisez une image de base contenant Java 8 et sbt installé
FROM openjdk:8-jdk-alpine

# Définir le répertoire de travail dans l'image
WORKDIR /app

# Copiez le fichier build.sbt et les sources dans le conteneur
COPY build.sbt .
COPY src ./src

# Exécutez sbt pour télécharger et installer les dépendances
RUN apk update && apk add --no-cache curl bash && \
    curl -Ls https://git.io/sbt > sbt && \
    chmod +x sbt && \
    ./sbt update

# Exécutez les tests
CMD ./sbt test

